services:
  server:
    build:
      context: ./KRAGEN_Dashboard/Backend
      dockerfile: Dockerfile
    # image: moorelab/${IMAGE_NAME}:${TAG}
    image: kragen-server:${TAG}
    container_name: kragen-server
    ports:
      - 5050:5050
    volumes:
      - "./:/app"
    working_dir: /app
    env_file:
      - .env
      - config/kragen.env
