services:
  kragen:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        docker_files: 'docker'
    image: kragen:${TAG}
    volumes:
      - "./:/app"
    working_dir: /app
    entrypoint: ["python", "src/kragen.py"]
    env_file:
      - .env
      - config/kragen.env
    command: test.csv
